#!/bin/bash

# check if root, when not define alias with sudo
if [[ $EUID -ne 0 ]]; then
  alias apt='sudo apt'
  alias reboot='sudo reboot'
  alias shutdown='sudo shutdown'
  alias systemctl='sudo systemctl'
  alias journalctl='sudo journalctl'
  alias service='sudo service'
fi

# ps tree / forest
alias ps='ps --forest'

# password generator
genpasswd() {
	local l=$1
    [ "$l" == "" ] && l=24
    tr -dc A-Za-z0-9_ < /dev/urandom | head -c ${l} | xargs
}

# Simplify apt search and install
function show () {
  apt-cache search $1
}

function giveme () {
  apt install "$@"
}

function extract () {
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2) tar xjf $1 ;;
      *.tar.gz) tar xzf $1 ;;
      *.bz2) bunzip2 $1 ;;
      *.rar) rar x $1 ;;
      *.gz) gunzip $1 ;;
      *.tar) tar xf $1 ;;
      *.tbz2) tar xjf $1 ;;
      *.tgz) tar xzf $1 ;;
      *.zip) unzip $1 ;;
      *.Z) uncompress $1 ;;
      *) echo "'$1' cannot be extracted via extract()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

function psg() {
  if [ ! -z $1 ] ; then
    echo "Grepping for processes matching $1..."
    ps aux | grep $1 
  else
    echo "!! Need name to grep for"
  fi
}

# bat alias
if [ -x ~/dotfiles/bin/bat ]; then
  alias cat='bat'
fi

# ls & lsd shortcuts
if [ -x ~/dotfiles/bin/lsd ]; then
  alias ls='lsd'
  alias l='lsd -lh'
  alias ll='lsd -lah'
  alias la='lsd -Ah'
  alias lt='lsd --tree'
else
  alias ls='ls --sort=extension --color=auto'
  alias l='ls -lh'
  alias ll='ls -lah'
  alias la='ls -A'
  alias lt='ls --tree'
fi

# cd - show content after cd
cd() { builtin cd "$@"; ls -lah; }
alias ..='cd ..'

# clear + motd
alias cls='source ~/.bashrc'
alias rl='source ~/.bashrc'
alias reload='source ~/.bashrc'

# dotfiles update
alias update-dotfiles='cd ~/dotfiles && git pull && rl'

# fast switch to dotfiles
alias dotf='cd ~/dotfiles && git status'

alias dotfu='dotf && gp && rl'

# system update
alias update='apt update && apt upgrade -y && apt autoremove -y && source ~/.bashrc'

# syslog tail -f / messages tail -f
if [[ $EUID -ne 0 ]]; then
  alias sysl='sudo tail -f /var/log/syslog'
  alias mesl='sudo tail -f /var/log/messages'
else
  alias sysl='tail -f /var/log/syslog'
  alias mesl='tail -f /var/log/messages'
fi

# dmesg (human readable time)
alias dmesg='dmesg -T'

# reboot
case $HOSTNAME in
  thor) alias reboot='powershell.exe -command restart-computer';;
esac

# shutdown
case $HOSTNAME in
  thor) alias shutdown='powershell.exe -command stop-computer';;
  *) alias shutdown='shutdown -h now';;
esac

# color for manpages
alias man="TERMINFO=~/.terminfo TERM=mostlike LESS=C PAGER=less man"

# color
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
  alias diff='colordiff'
fi

# fix typo mistakes
alias cd.='cd ..'
alias cd..='cd ..'

# watch, 1s default
alias watch='watch -n1'

# wol
alias wol-thor='/usr/bin/wakeonlan -i 10.1.1.2 0c:9d:92:84:86:49'
alias wol-pve01='/usr/bin/wakeonlan -i 192.168.1.50 1c:69:7a:02:5e:3f'
alias wol-pve02='/usr/bin/wakeonlan -i 192.168.1.51 1c:69:7a:62:9b:95'

# locate
if [ -x /usr/bin/locate ]; then
  alias loc='locate -A -i'
fi