#!/bin/bash

# load git-prompt
if [ -f /etc/bash_completion.d/git-prompt ]; then
    source /etc/bash_completion.d/git-prompt
fi

# Very useful for stash handling
function show-stash() 
{
    git stash show -p stash@{$1};
}

function stash-len() 
{
    git stash list | wc -l;
}

function drop-stash() 
{
    git stash drop stash@{$1};
}

alias ga='git add'
alias gb='git br' 
alias gd='git diff' 
alias gdc='git diff --cached' 
alias gl='git log'
alias gp='git pull' 
alias gs='git status' 
alias gst='git stash' 
alias gplo='git pull origin master'
alias gpo='git push origin master'
alias gbv='git branch -vv' 
alias gr='git reflog'
alias glf='git ls-files'

# Useful when working on a branch and 
# want to summarize changes against master
alias gdmno='git diff master  --name-only'
