#!/bin/bash

export COLOR_BLUE="\e[38;5;39m"
export COLOR_LIGHT_BLUE="\e[38;5;81m"
export COLOR_RED="\e[38;5;196m"
export COLOR_GREEN="\e[38;5;83m"
export COLOR_GREEN_BOLD="\e[1;38;5;83m"
export COLOR_YELLOW="\e[38;5;227m"
export COLOR_WHITE="\e[37m"
export COLOR_ORANGE="\e[38;5;214m"
export COLOR_PURPLE="\e[38;5;99m"
export COLOR_CLOSE="$(tput sgr0)"
export COLOR_RESET="\033[m"