#!/bin/bash

#
# SET DEFAULT EDITORS
#
export EDITOR='vim'
export ALTERNATE_EDITOR='vim'
export VISUAL='vim'

#
# SET COLORS (https://bashcolors.com)
#
source $HOME/dotfiles/config/dotfiles.config

#
# SET NAVI OPTIONS
#
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'

#
# SET HISTORY OPTIONS
#
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups
export HISTCONTROL=ignoreboth
export HISTIGNORE='&:clear:ls:cd:[bf]g:exit:[ t\]*'
export HISTSIZE=100000
export HISTFILESIZE=2000000
shopt -s histappend                                                                # Append to the history file, don't overwrite it
export PROMPT_COMMAND="history -a;history -c; history -r; $PROMPT_COMMAND"         # Save and reload history after each command finishes

#
# ENABLE COLOR PROMPT
#
if [ -n "$force_color_prompt" ]; then
  if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
    color_prompt=yes
  else
    color_prompt=
  fi
fi

#
# SET KEY-BINDINGS (-o vi || -o emacs)
# 
set -o emacs

#
# Check the window size after each command and, if necessary, update the values of LINES and COLUMNS.
#
shopt -s checkwinsize

#
# Make less more friendly for non-text input files, see lesspipe(1)
#
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Set variable identifying the chroot you work in
# (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
  debian_chroot=$(cat /etc/debian_chroot)
fi

#
# ENABLE TAB COMPLETION
#
if [ -f /etc/bash_completion ]; then
  source /etc/bash_completion
fi
if [ -f /etc/profile.d/bash_completion.sh ]; then
  # byobu (https://wiki.ubuntuusers.de/byobu/#Autovervollstaendigung-aktivieren)
  source /etc/profile.d/bash_completion.sh
fi

#
# ENABLE TAB COMPLETION FOR SUDO
#
complete -cf sudo

# If this is an xterm set the title to user@host:dir
case "$TERM" in
  xterm*|rxvt*)
    PROMPT_COMMAND='printf "\033]0;%s@%s:%s\033\\" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/~}"'
  ;;
  screen*)
    PROMPT_COMMAND='CURDIR=`basename ${PWD}`;echo -ne "\033]0;${USER}@${HOSTNAME}:\007\033k${CURDIR}\033\\"'
  ;;
*)
;;
esac

#
# CDPATH
# https://www.oreilly.com/library/view/bash-cookbook/0596526784/ch16s05.html
#
export CDPATH='.:~/dotfiles'