#!/usr/bin/env bash
# simple bash prompt by koljah
# https://github.com/koljah-de/simple-bash-prompt/
#
# modified by darkiop

#
# SET PROMPT COLORS
#
COLOR_BRACKET=$blue_color
COLOR_COMMAND=$white_color
COLOR_DEVICE=$blue_color
COLOR_DIR=$orange_color
COLOR_USER=$light_blue_color
COLOR_SEPARATOR=$white_color
COLOR_RESET=$white_color
COLOR_DATE=$green_color
COLOR_GIT=$yellow_color
COLOR_GIT_BRANCH=$yellow_color
COLOR_SUDO_ACTIVE=$purple_color
COLOR_SSH_ACTIVE=$purple_color
if [ "${EUID}" -ne 0 ]; then
  COLOR_SYMBOL=$white_color
else
  # root
  COLOR_SYMBOL=$red_color
fi

# define the prompt terminator character
SYMBOL="\\$"

# set the color with the exit status of the last command
COLOR_EXIT_STATUS () {
  if [ $1 -eq 0 ]; then
    echo -e $blue_color
  else
    echo -e $red_color
  fi
}

# git: check if current directory is a git repo
CHECK_IF_GIT_REPO () {
  git rev-parse 2> /dev/null
}

# git: print the branch
GIT_BRANCH () {
  simple_bash_prompt_git_branch=$(git rev-parse --abbrev-ref HEAD 2> /dev/null)
  if [ "$simple_bash_prompt_git_branch" = "HEAD" ]; then
    echo "no branch"
   else
    echo $simple_bash_prompt_git_branch
  fi
}

# check sudo
CHECK_IF_SUDO_IS_ACTIVE () {
  CAN_I_RUN_SUDO=$(sudo -n uptime 2>&1 | grep "load" | wc -l)
  if [ ${CAN_I_RUN_SUDO} -gt 0 ]; then
    return 0 # true
  else
    return 1 # false
  fi
}

# check if ssh session
# https://unix.stackexchange.com/questions/9605/how-can-i-detect-if-the-shell-is-controlled-from-ssh
CHECK_IF_SSH_SESSION () {
  if [[ $(who am i) =~ \([-a-zA-Z0-9\.]+\)$ ]]; then
    return 0 # true
  else
    return 1 # false
  fi
}

# 
# BUILD THE PROMPT
# \n = new line
# \u = user
# \h = time
# \w = current dir
#

BUILD_PROMPT () {
CHECK_EXIT_STATUS=$?
BASH_PROMPT=$(COLOR_EXIT_STATUS $CHECK_EXIT_STATUS)"┬ "
BASH_PROMPT+=$COLOR_BRACKET"["
if $(CHECK_IF_SSH_SESSION); then
BASH_PROMPT+=$COLOR_SSH_ACTIVE"ssh"$COLOR_SEPARATOR":"
fi
BASH_PROMPT+=$COLOR_USER"\u"$COLOR_SEPARATOR"@"$COLOR_DEVICE"\h"
BASH_PROMPT+=$COLOR_SEPARATOR":"
BASH_PROMPT+=$COLOR_DIR"\w"
BASH_PROMPT+=$COLOR_BRACKET"]"
#BASH_PROMPT+=$(COLOR_EXIT_STATUS $CHECK_EXIT_STATUS)"-"
BASH_PROMPT+=" "
BASH_PROMPT+=$COLOR_BRACKET"["
BASH_PROMPT+=$(COLOR_EXIT_STATUS $CHECK_EXIT_STATUS)$COLOR_DATE"\t"
BASH_PROMPT+=$COLOR_BRACKET"]"
if $(CHECK_IF_GIT_REPO); then
#BASH_PROMPT+=$(COLOR_EXIT_STATUS $CHECK_EXIT_STATUS)"-"
BASH_PROMPT+=" "
BASH_PROMPT+=$COLOR_BRACKET"["
BASH_PROMPT+=$COLOR_GIT_BRANCH"git:$(GIT_BRANCH)"
BASH_PROMPT+=$COLOR_BRACKET"]"
fi
if $(CHECK_IF_SUDO_IS_ACTIVE); then
#BASH_PROMPT+=$(COLOR_EXIT_STATUS $CHECK_EXIT_STATUS)"-"
BASH_PROMPT+=" "
BASH_PROMPT+=$COLOR_BRACKET"["
BASH_PROMPT+=$COLOR_SUDO_ACTIVE"sudo-active"
BASH_PROMPT+=$COLOR_BRACKET"]"
fi
BASH_PROMPT+="\n"$(COLOR_EXIT_STATUS $CHECK_EXIT_STATUS)"╰─> "$COLOR_SYMBOL$SYMBOL$COLOR_COMMAND" "
PS1=$BASH_PROMPT
}

export PROMPT_COMMAND=BUILD_PROMPT