#!/usr/bin/env zsh

if [[ -z "${ZSH_VERSION:-}" ]]; then
  return 0
fi

case $- in
  *i*) ;;
  *) return ;;
esac

# Editor
export EDITOR='vim'
export ALTERNATE_EDITOR='vim'
export VISUAL='vim'

# History
HISTSIZE=100000
SAVEHIST=2000000
HISTFILE="${HOME}/.zsh_history"
setopt APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_SAVE_NO_DUPS

# Key bindings (emacs)
bindkey -e

setopt AUTO_CD
