#!/bin/bash

# check if root, when not define alias with sudo
if [[ ${EUID} -ne 0 ]]; then
  alias gstatus='sudo gstatus'
  alias gluster='sudo gluster'
fi

# volume info
alias gvi='gstatus -ab && gluster volume heal gfs-pve info'

alias gvi-watch="watch -n1 'sudo gstatus -ab && sudo gluster volume heal gfs-pve info'"