#!/bin/bash

# check if root, when not define alias with sudo
if [[ ${EUID} -ne 0 ]]; then
	alias docker='sudo '$(which docker)
	alias docker-compose='sudo '$(which docker-compose)
fi

alias dk='docker'
alias dklc='docker ps -l'                                                            # List last Docker container
alias dklcid='docker ps -l -q'                                                       # List last Docker container ID
alias dklcip='docker inspect -f "{{.NetworkSettings.IPAddress}}" $(docker ps -l -q)' # Get IP of last Docker container
alias dkps='docker ps'                                                               # List running Docker containers
alias dkpsa='docker ps -a'                                                           # List all Docker containers
alias dki='docker images'                                                            # List Docker images
alias dkrmac='docker rm $(docker ps -a -q)'                                          # Delete all Docker containers
alias dkrmui='docker images -q -f dangling=true | xargs -r docker rmi'               # Delete all untagged Docker images
alias dkelc='docker exec -it $(dklcid) bash --login'                                 # Enter last container (works with Docker 1.3 and above)
alias dkrmflast='docker rm -f $(dklcid)'
alias dkbash='dkelc'
alias dkex='docker exec -it '                                                        # Useful to run any commands into container without leaving host
alias dkri='docker run --rm -i '
alias dkrit='docker run --rm -it '
alias dkip='docker image prune -a -f'
alias dkvp='docker volume prune -f'
alias dksp='docker system prune -a -f'

# https://docs.docker.com/engine/reference/commandline/ps/
alias dps="docker ps --format 'table {{.Names}}\t{{.Image}}' | sort -n"
alias dpsa="docker ps -a --format 'table {{.Names}}\t{{.Image}}' | sort -n"
